fix ChangeVision/astah-emf#9755 スクリプトエディタのダークモードの対応
ChangeVision/astah-script-plugin pull request #36
Opened 2022-08-23 08:40 UTC by astah-harry

ChangeVision/astah-emf#9755

ChangeVision/astah-emf#9757 と一緒にアクセプトしてください

2022-08-25 00:31 UTC, aasakawa requested changes

2022-08-25 00:31 UTC, aasakawa commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +        } catch (ClassNotFoundException | InvalidUsingException e) {
`pom.xml` の前提バージョンを上げるか、 `NoSuchMethodError` を catch しないと、旧バージョンでプラグインを動作させた場合に例外になると思いますが、前提バージョンだと Pro 系と ASY が別物で回避できないので、後者で回避するのだと思います。

2022-08-25 00:31 UTC, aasakawa commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +            path = path.replaceAll("\\.([^.]+)$", "\\$" + "dark" + ".$1");
@kamura @y-zhou @astah-harry この修正を全プラグインにばらまくことになってしまいますよね。
`URL getResourceForLookAndFeel(ClassLoader, String)` のような API を追加するのはどうでしょう？

2022-08-25 00:33 UTC, y-zhou commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +            path = path.replaceAll("\\.([^.]+)$", "\\$" + "dark" + ".$1");
@aasakawa @astah-harry  @kamura 
各Pluginの対応が必要と考えれば、一か所で全問題が解決できると嬉しいです。

2022-08-25 02:59 UTC, astah-harry commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +            path = path.replaceAll("\\.([^.]+)$", "\\$" + "dark" + ".$1");
@aasakawa @kamura @y-zhou `IIconManager`に`URL getResourceForLookAndFeel(ClassLoader, String)`を追加しますか？
ダークモードの場合、ダークモード用アイコンのURLを返ります

2022-08-25 03:02 UTC, astah-harry commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +        } catch (ClassNotFoundException | InvalidUsingException e) {
@aasakawa 確認ですが、
pom.xmlで`<astah.version>7.2</astah.version>` をバージョン上げるしたほうがいいという意味ですね？

2022-08-25 03:10 UTC, astah-harry commented
@astah-harry test

2022-08-25 04:01 UTC, aasakawa commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +        } catch (ClassNotFoundException | InvalidUsingException e) {
逆です。 `<astah.version>` では対処できないので、 `NoSuchMethodError` を catch するしかありません。

2022-08-25 04:03 UTC, astah-harry commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +        } catch (ClassNotFoundException | InvalidUsingException e) {
@aasakawa はい、分かりました

2022-08-25 04:23 UTC, aasakawa commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +            path = path.replaceAll("\\.([^.]+)$", "\\$" + "dark" + ".$1");
@astah-harry @kamura @y-zhou こんなインタフェースあったのですね。知りませんでした。
ASY だと今のところ `UnsupportedOperationException` ですね。

URL を対象にファイル名を調整するのでアイコンとは限らない点が気になります。
ここに置くのならば、 `Icon getIcon(ClassLoader, String)` の方が良さそうに思います。

他にも、 `ILookAndFeelManager` を導入して L&F まわりをまとめる方向も考えられますね。

2022-08-25 05:36 UTC, astah-harry commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +            path = path.replaceAll("\\.([^.]+)$", "\\$" + "dark" + ".$1");
@aasakawa @kamura @y-zhou `ILookAndFeelManager `を導入するのは良さそうです、
`boolean isDarkLookAndFeel()`と`Icon getIcon(ClassLoader, String)`両方を`ILookAndFeelManager`に追加する

2022-08-26 00:37 UTC, astah-harry commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +            path = path.replaceAll("\\.([^.]+)$", "\\$" + "dark" + ".$1");
@aasakawa すみません、朝会で何を決めましたか？現在の`ILookAndFeelManager `はなんか修正必要ですか？

2022-08-26 01:12 UTC, aasakawa commented on src/main/java/com/change_vision/astah/extension/plugin/script/ScriptView.java
> +            path = path.replaceAll("\\.([^.]+)$", "\\$" + "dark" + ".$1");
@astah-harry (Cc @kamura ) 以下と思っています。

- `ILookAndFeelManager` を導入する
- `URL ILookAndFeelManager.getResource(ClassLoader, String)` も追加する(`getIcon()` はこれを使う)
- `getResource()` では `$light` 付きのファイルも考慮する(ASY 内部のコードと同様の動作にする)

2022-09-08 02:45 UTC, merged